// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbGetTickTransactionsStatusResponse pb get tick transactions status response
//
// swagger:model pbGetTickTransactionsStatusResponse
type PbGetTickTransactionsStatusResponse struct {

	// transactions status
	TransactionsStatus []*PbTransactionStatus `json:"transactionsStatus"`
}

// Validate validates this pb get tick transactions status response
func (m *PbGetTickTransactionsStatusResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTransactionsStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PbGetTickTransactionsStatusResponse) validateTransactionsStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.TransactionsStatus) { // not required
		return nil
	}

	for i := 0; i < len(m.TransactionsStatus); i++ {
		if swag.IsZero(m.TransactionsStatus[i]) { // not required
			continue
		}

		if m.TransactionsStatus[i] != nil {
			if err := m.TransactionsStatus[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("transactionsStatus" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("transactionsStatus" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this pb get tick transactions status response based on the context it is used
func (m *PbGetTickTransactionsStatusResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTransactionsStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PbGetTickTransactionsStatusResponse) contextValidateTransactionsStatus(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.TransactionsStatus); i++ {

		if m.TransactionsStatus[i] != nil {

			if swag.IsZero(m.TransactionsStatus[i]) { // not required
				return nil
			}

			if err := m.TransactionsStatus[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("transactionsStatus" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("transactionsStatus" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PbGetTickTransactionsStatusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbGetTickTransactionsStatusResponse) UnmarshalBinary(b []byte) error {
	var res PbGetTickTransactionsStatusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
