// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbGetStatusResponse pb get status response
//
// swagger:model pbGetStatusResponse
type PbGetStatusResponse struct {

	// last processed tick
	LastProcessedTick *PbProcessedTick `json:"lastProcessedTick,omitempty"`

	// last processed ticks per epoch
	LastProcessedTicksPerEpoch map[string]int64 `json:"lastProcessedTicksPerEpoch,omitempty"`

	// skipped ticks
	SkippedTicks []*PbSkippedTicksInterval `json:"skippedTicks"`
}

// Validate validates this pb get status response
func (m *PbGetStatusResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastProcessedTick(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSkippedTicks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PbGetStatusResponse) validateLastProcessedTick(formats strfmt.Registry) error {
	if swag.IsZero(m.LastProcessedTick) { // not required
		return nil
	}

	if m.LastProcessedTick != nil {
		if err := m.LastProcessedTick.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("lastProcessedTick")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("lastProcessedTick")
			}
			return err
		}
	}

	return nil
}

func (m *PbGetStatusResponse) validateSkippedTicks(formats strfmt.Registry) error {
	if swag.IsZero(m.SkippedTicks) { // not required
		return nil
	}

	for i := 0; i < len(m.SkippedTicks); i++ {
		if swag.IsZero(m.SkippedTicks[i]) { // not required
			continue
		}

		if m.SkippedTicks[i] != nil {
			if err := m.SkippedTicks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("skippedTicks" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("skippedTicks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this pb get status response based on the context it is used
func (m *PbGetStatusResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLastProcessedTick(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSkippedTicks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PbGetStatusResponse) contextValidateLastProcessedTick(ctx context.Context, formats strfmt.Registry) error {

	if m.LastProcessedTick != nil {

		if swag.IsZero(m.LastProcessedTick) { // not required
			return nil
		}

		if err := m.LastProcessedTick.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("lastProcessedTick")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("lastProcessedTick")
			}
			return err
		}
	}

	return nil
}

func (m *PbGetStatusResponse) contextValidateSkippedTicks(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SkippedTicks); i++ {

		if m.SkippedTicks[i] != nil {

			if swag.IsZero(m.SkippedTicks[i]) { // not required
				return nil
			}

			if err := m.SkippedTicks[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("skippedTicks" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("skippedTicks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PbGetStatusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbGetStatusResponse) UnmarshalBinary(b []byte) error {
	var res PbGetStatusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
