// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbTransactionStatus pb transaction status
//
// swagger:model pbTransactionStatus
type PbTransactionStatus struct {

	// money flew
	MoneyFlew bool `json:"moneyFlew,omitempty"`

	// tx Id
	TxID string `json:"txId,omitempty"`
}

// Validate validates this pb transaction status
func (m *PbTransactionStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb transaction status based on context it is used
func (m *PbTransactionStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbTransactionStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbTransactionStatus) UnmarshalBinary(b []byte) error {
	var res PbTransactionStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
