// Code generated by go-swagger; DO NOT EDIT.

package tx_status_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTxStatusServiceGetTransactionStatusParams creates a new TxStatusServiceGetTransactionStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTxStatusServiceGetTransactionStatusParams() *TxStatusServiceGetTransactionStatusParams {
	return &TxStatusServiceGetTransactionStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTxStatusServiceGetTransactionStatusParamsWithTimeout creates a new TxStatusServiceGetTransactionStatusParams object
// with the ability to set a timeout on a request.
func NewTxStatusServiceGetTransactionStatusParamsWithTimeout(timeout time.Duration) *TxStatusServiceGetTransactionStatusParams {
	return &TxStatusServiceGetTransactionStatusParams{
		timeout: timeout,
	}
}

// NewTxStatusServiceGetTransactionStatusParamsWithContext creates a new TxStatusServiceGetTransactionStatusParams object
// with the ability to set a context for a request.
func NewTxStatusServiceGetTransactionStatusParamsWithContext(ctx context.Context) *TxStatusServiceGetTransactionStatusParams {
	return &TxStatusServiceGetTransactionStatusParams{
		Context: ctx,
	}
}

// NewTxStatusServiceGetTransactionStatusParamsWithHTTPClient creates a new TxStatusServiceGetTransactionStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewTxStatusServiceGetTransactionStatusParamsWithHTTPClient(client *http.Client) *TxStatusServiceGetTransactionStatusParams {
	return &TxStatusServiceGetTransactionStatusParams{
		HTTPClient: client,
	}
}

/*
TxStatusServiceGetTransactionStatusParams contains all the parameters to send to the API endpoint

	for the tx status service get transaction status operation.

	Typically these are written to a http.Request.
*/
type TxStatusServiceGetTransactionStatusParams struct {

	// TxID.
	TxID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the tx status service get transaction status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TxStatusServiceGetTransactionStatusParams) WithDefaults() *TxStatusServiceGetTransactionStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the tx status service get transaction status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TxStatusServiceGetTransactionStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the tx status service get transaction status params
func (o *TxStatusServiceGetTransactionStatusParams) WithTimeout(timeout time.Duration) *TxStatusServiceGetTransactionStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tx status service get transaction status params
func (o *TxStatusServiceGetTransactionStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tx status service get transaction status params
func (o *TxStatusServiceGetTransactionStatusParams) WithContext(ctx context.Context) *TxStatusServiceGetTransactionStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tx status service get transaction status params
func (o *TxStatusServiceGetTransactionStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tx status service get transaction status params
func (o *TxStatusServiceGetTransactionStatusParams) WithHTTPClient(client *http.Client) *TxStatusServiceGetTransactionStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tx status service get transaction status params
func (o *TxStatusServiceGetTransactionStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTxID adds the txID to the tx status service get transaction status params
func (o *TxStatusServiceGetTransactionStatusParams) WithTxID(txID string) *TxStatusServiceGetTransactionStatusParams {
	o.SetTxID(txID)
	return o
}

// SetTxID adds the txId to the tx status service get transaction status params
func (o *TxStatusServiceGetTransactionStatusParams) SetTxID(txID string) {
	o.TxID = txID
}

// WriteToRequest writes these params to a swagger request
func (o *TxStatusServiceGetTransactionStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param txId
	if err := r.SetPathParam("txId", o.TxID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
