// Code generated by go-swagger; DO NOT EDIT.

package tx_status_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTxStatusServiceGetStatusParams creates a new TxStatusServiceGetStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTxStatusServiceGetStatusParams() *TxStatusServiceGetStatusParams {
	return &TxStatusServiceGetStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTxStatusServiceGetStatusParamsWithTimeout creates a new TxStatusServiceGetStatusParams object
// with the ability to set a timeout on a request.
func NewTxStatusServiceGetStatusParamsWithTimeout(timeout time.Duration) *TxStatusServiceGetStatusParams {
	return &TxStatusServiceGetStatusParams{
		timeout: timeout,
	}
}

// NewTxStatusServiceGetStatusParamsWithContext creates a new TxStatusServiceGetStatusParams object
// with the ability to set a context for a request.
func NewTxStatusServiceGetStatusParamsWithContext(ctx context.Context) *TxStatusServiceGetStatusParams {
	return &TxStatusServiceGetStatusParams{
		Context: ctx,
	}
}

// NewTxStatusServiceGetStatusParamsWithHTTPClient creates a new TxStatusServiceGetStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewTxStatusServiceGetStatusParamsWithHTTPClient(client *http.Client) *TxStatusServiceGetStatusParams {
	return &TxStatusServiceGetStatusParams{
		HTTPClient: client,
	}
}

/*
TxStatusServiceGetStatusParams contains all the parameters to send to the API endpoint

	for the tx status service get status operation.

	Typically these are written to a http.Request.
*/
type TxStatusServiceGetStatusParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the tx status service get status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TxStatusServiceGetStatusParams) WithDefaults() *TxStatusServiceGetStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the tx status service get status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TxStatusServiceGetStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the tx status service get status params
func (o *TxStatusServiceGetStatusParams) WithTimeout(timeout time.Duration) *TxStatusServiceGetStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tx status service get status params
func (o *TxStatusServiceGetStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tx status service get status params
func (o *TxStatusServiceGetStatusParams) WithContext(ctx context.Context) *TxStatusServiceGetStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tx status service get status params
func (o *TxStatusServiceGetStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tx status service get status params
func (o *TxStatusServiceGetStatusParams) WithHTTPClient(client *http.Client) *TxStatusServiceGetStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tx status service get status params
func (o *TxStatusServiceGetStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *TxStatusServiceGetStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
