// Code generated by go-swagger; DO NOT EDIT.

package tx_status_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTxStatusServiceGetTickTransactionsStatusParams creates a new TxStatusServiceGetTickTransactionsStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTxStatusServiceGetTickTransactionsStatusParams() *TxStatusServiceGetTickTransactionsStatusParams {
	return &TxStatusServiceGetTickTransactionsStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTxStatusServiceGetTickTransactionsStatusParamsWithTimeout creates a new TxStatusServiceGetTickTransactionsStatusParams object
// with the ability to set a timeout on a request.
func NewTxStatusServiceGetTickTransactionsStatusParamsWithTimeout(timeout time.Duration) *TxStatusServiceGetTickTransactionsStatusParams {
	return &TxStatusServiceGetTickTransactionsStatusParams{
		timeout: timeout,
	}
}

// NewTxStatusServiceGetTickTransactionsStatusParamsWithContext creates a new TxStatusServiceGetTickTransactionsStatusParams object
// with the ability to set a context for a request.
func NewTxStatusServiceGetTickTransactionsStatusParamsWithContext(ctx context.Context) *TxStatusServiceGetTickTransactionsStatusParams {
	return &TxStatusServiceGetTickTransactionsStatusParams{
		Context: ctx,
	}
}

// NewTxStatusServiceGetTickTransactionsStatusParamsWithHTTPClient creates a new TxStatusServiceGetTickTransactionsStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewTxStatusServiceGetTickTransactionsStatusParamsWithHTTPClient(client *http.Client) *TxStatusServiceGetTickTransactionsStatusParams {
	return &TxStatusServiceGetTickTransactionsStatusParams{
		HTTPClient: client,
	}
}

/*
TxStatusServiceGetTickTransactionsStatusParams contains all the parameters to send to the API endpoint

	for the tx status service get tick transactions status operation.

	Typically these are written to a http.Request.
*/
type TxStatusServiceGetTickTransactionsStatusParams struct {

	// TickNumber.
	//
	// Format: int64
	TickNumber int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the tx status service get tick transactions status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TxStatusServiceGetTickTransactionsStatusParams) WithDefaults() *TxStatusServiceGetTickTransactionsStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the tx status service get tick transactions status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TxStatusServiceGetTickTransactionsStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the tx status service get tick transactions status params
func (o *TxStatusServiceGetTickTransactionsStatusParams) WithTimeout(timeout time.Duration) *TxStatusServiceGetTickTransactionsStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tx status service get tick transactions status params
func (o *TxStatusServiceGetTickTransactionsStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tx status service get tick transactions status params
func (o *TxStatusServiceGetTickTransactionsStatusParams) WithContext(ctx context.Context) *TxStatusServiceGetTickTransactionsStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tx status service get tick transactions status params
func (o *TxStatusServiceGetTickTransactionsStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tx status service get tick transactions status params
func (o *TxStatusServiceGetTickTransactionsStatusParams) WithHTTPClient(client *http.Client) *TxStatusServiceGetTickTransactionsStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tx status service get tick transactions status params
func (o *TxStatusServiceGetTickTransactionsStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTickNumber adds the tickNumber to the tx status service get tick transactions status params
func (o *TxStatusServiceGetTickTransactionsStatusParams) WithTickNumber(tickNumber int64) *TxStatusServiceGetTickTransactionsStatusParams {
	o.SetTickNumber(tickNumber)
	return o
}

// SetTickNumber adds the tickNumber to the tx status service get tick transactions status params
func (o *TxStatusServiceGetTickTransactionsStatusParams) SetTickNumber(tickNumber int64) {
	o.TickNumber = tickNumber
}

// WriteToRequest writes these params to a swagger request
func (o *TxStatusServiceGetTickTransactionsStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tickNumber
	if err := r.SetPathParam("tickNumber", swag.FormatInt64(o.TickNumber)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
