// Code generated by go-swagger; DO NOT EDIT.

package tx_status_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qubic/integration/UseCases/go-clients/tx-status/models"
)

// TxStatusServiceGetStatusReader is a Reader for the TxStatusServiceGetStatus structure.
type TxStatusServiceGetStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TxStatusServiceGetStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTxStatusServiceGetStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewTxStatusServiceGetStatusDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTxStatusServiceGetStatusOK creates a TxStatusServiceGetStatusOK with default headers values
func NewTxStatusServiceGetStatusOK() *TxStatusServiceGetStatusOK {
	return &TxStatusServiceGetStatusOK{}
}

/*
TxStatusServiceGetStatusOK describes a response with status code 200, with default header values.

A successful response.
*/
type TxStatusServiceGetStatusOK struct {
	Payload *models.PbGetStatusResponse
}

// IsSuccess returns true when this tx status service get status o k response has a 2xx status code
func (o *TxStatusServiceGetStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this tx status service get status o k response has a 3xx status code
func (o *TxStatusServiceGetStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this tx status service get status o k response has a 4xx status code
func (o *TxStatusServiceGetStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this tx status service get status o k response has a 5xx status code
func (o *TxStatusServiceGetStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this tx status service get status o k response a status code equal to that given
func (o *TxStatusServiceGetStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the tx status service get status o k response
func (o *TxStatusServiceGetStatusOK) Code() int {
	return 200
}

func (o *TxStatusServiceGetStatusOK) Error() string {
	return fmt.Sprintf("[GET /tx-status/status][%d] txStatusServiceGetStatusOK  %+v", 200, o.Payload)
}

func (o *TxStatusServiceGetStatusOK) String() string {
	return fmt.Sprintf("[GET /tx-status/status][%d] txStatusServiceGetStatusOK  %+v", 200, o.Payload)
}

func (o *TxStatusServiceGetStatusOK) GetPayload() *models.PbGetStatusResponse {
	return o.Payload
}

func (o *TxStatusServiceGetStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PbGetStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTxStatusServiceGetStatusDefault creates a TxStatusServiceGetStatusDefault with default headers values
func NewTxStatusServiceGetStatusDefault(code int) *TxStatusServiceGetStatusDefault {
	return &TxStatusServiceGetStatusDefault{
		_statusCode: code,
	}
}

/*
TxStatusServiceGetStatusDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type TxStatusServiceGetStatusDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this tx status service get status default response has a 2xx status code
func (o *TxStatusServiceGetStatusDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this tx status service get status default response has a 3xx status code
func (o *TxStatusServiceGetStatusDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this tx status service get status default response has a 4xx status code
func (o *TxStatusServiceGetStatusDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this tx status service get status default response has a 5xx status code
func (o *TxStatusServiceGetStatusDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this tx status service get status default response a status code equal to that given
func (o *TxStatusServiceGetStatusDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the tx status service get status default response
func (o *TxStatusServiceGetStatusDefault) Code() int {
	return o._statusCode
}

func (o *TxStatusServiceGetStatusDefault) Error() string {
	return fmt.Sprintf("[GET /tx-status/status][%d] TxStatusService_GetStatus default  %+v", o._statusCode, o.Payload)
}

func (o *TxStatusServiceGetStatusDefault) String() string {
	return fmt.Sprintf("[GET /tx-status/status][%d] TxStatusService_GetStatus default  %+v", o._statusCode, o.Payload)
}

func (o *TxStatusServiceGetStatusDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *TxStatusServiceGetStatusDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
