// Code generated by go-swagger; DO NOT EDIT.

package qubic_live_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/qubic/integration/go-clients/live/models"
)

// NewQubicLiveServiceBroadcastTransactionParams creates a new QubicLiveServiceBroadcastTransactionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQubicLiveServiceBroadcastTransactionParams() *QubicLiveServiceBroadcastTransactionParams {
	return &QubicLiveServiceBroadcastTransactionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQubicLiveServiceBroadcastTransactionParamsWithTimeout creates a new QubicLiveServiceBroadcastTransactionParams object
// with the ability to set a timeout on a request.
func NewQubicLiveServiceBroadcastTransactionParamsWithTimeout(timeout time.Duration) *QubicLiveServiceBroadcastTransactionParams {
	return &QubicLiveServiceBroadcastTransactionParams{
		timeout: timeout,
	}
}

// NewQubicLiveServiceBroadcastTransactionParamsWithContext creates a new QubicLiveServiceBroadcastTransactionParams object
// with the ability to set a context for a request.
func NewQubicLiveServiceBroadcastTransactionParamsWithContext(ctx context.Context) *QubicLiveServiceBroadcastTransactionParams {
	return &QubicLiveServiceBroadcastTransactionParams{
		Context: ctx,
	}
}

// NewQubicLiveServiceBroadcastTransactionParamsWithHTTPClient creates a new QubicLiveServiceBroadcastTransactionParams object
// with the ability to set a custom HTTPClient for a request.
func NewQubicLiveServiceBroadcastTransactionParamsWithHTTPClient(client *http.Client) *QubicLiveServiceBroadcastTransactionParams {
	return &QubicLiveServiceBroadcastTransactionParams{
		HTTPClient: client,
	}
}

/*
QubicLiveServiceBroadcastTransactionParams contains all the parameters to send to the API endpoint

	for the qubic live service broadcast transaction operation.

	Typically these are written to a http.Request.
*/
type QubicLiveServiceBroadcastTransactionParams struct {

	// Body.
	Body *models.PbBroadcastTransactionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the qubic live service broadcast transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QubicLiveServiceBroadcastTransactionParams) WithDefaults() *QubicLiveServiceBroadcastTransactionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the qubic live service broadcast transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QubicLiveServiceBroadcastTransactionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the qubic live service broadcast transaction params
func (o *QubicLiveServiceBroadcastTransactionParams) WithTimeout(timeout time.Duration) *QubicLiveServiceBroadcastTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the qubic live service broadcast transaction params
func (o *QubicLiveServiceBroadcastTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the qubic live service broadcast transaction params
func (o *QubicLiveServiceBroadcastTransactionParams) WithContext(ctx context.Context) *QubicLiveServiceBroadcastTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the qubic live service broadcast transaction params
func (o *QubicLiveServiceBroadcastTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the qubic live service broadcast transaction params
func (o *QubicLiveServiceBroadcastTransactionParams) WithHTTPClient(client *http.Client) *QubicLiveServiceBroadcastTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the qubic live service broadcast transaction params
func (o *QubicLiveServiceBroadcastTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the qubic live service broadcast transaction params
func (o *QubicLiveServiceBroadcastTransactionParams) WithBody(body *models.PbBroadcastTransactionRequest) *QubicLiveServiceBroadcastTransactionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the qubic live service broadcast transaction params
func (o *QubicLiveServiceBroadcastTransactionParams) SetBody(body *models.PbBroadcastTransactionRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *QubicLiveServiceBroadcastTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
