// Code generated by go-swagger; DO NOT EDIT.

package qubic_live_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQubicLiveServiceGetBalanceParams creates a new QubicLiveServiceGetBalanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQubicLiveServiceGetBalanceParams() *QubicLiveServiceGetBalanceParams {
	return &QubicLiveServiceGetBalanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQubicLiveServiceGetBalanceParamsWithTimeout creates a new QubicLiveServiceGetBalanceParams object
// with the ability to set a timeout on a request.
func NewQubicLiveServiceGetBalanceParamsWithTimeout(timeout time.Duration) *QubicLiveServiceGetBalanceParams {
	return &QubicLiveServiceGetBalanceParams{
		timeout: timeout,
	}
}

// NewQubicLiveServiceGetBalanceParamsWithContext creates a new QubicLiveServiceGetBalanceParams object
// with the ability to set a context for a request.
func NewQubicLiveServiceGetBalanceParamsWithContext(ctx context.Context) *QubicLiveServiceGetBalanceParams {
	return &QubicLiveServiceGetBalanceParams{
		Context: ctx,
	}
}

// NewQubicLiveServiceGetBalanceParamsWithHTTPClient creates a new QubicLiveServiceGetBalanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewQubicLiveServiceGetBalanceParamsWithHTTPClient(client *http.Client) *QubicLiveServiceGetBalanceParams {
	return &QubicLiveServiceGetBalanceParams{
		HTTPClient: client,
	}
}

/*
QubicLiveServiceGetBalanceParams contains all the parameters to send to the API endpoint

	for the qubic live service get balance operation.

	Typically these are written to a http.Request.
*/
type QubicLiveServiceGetBalanceParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the qubic live service get balance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QubicLiveServiceGetBalanceParams) WithDefaults() *QubicLiveServiceGetBalanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the qubic live service get balance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QubicLiveServiceGetBalanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the qubic live service get balance params
func (o *QubicLiveServiceGetBalanceParams) WithTimeout(timeout time.Duration) *QubicLiveServiceGetBalanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the qubic live service get balance params
func (o *QubicLiveServiceGetBalanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the qubic live service get balance params
func (o *QubicLiveServiceGetBalanceParams) WithContext(ctx context.Context) *QubicLiveServiceGetBalanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the qubic live service get balance params
func (o *QubicLiveServiceGetBalanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the qubic live service get balance params
func (o *QubicLiveServiceGetBalanceParams) WithHTTPClient(client *http.Client) *QubicLiveServiceGetBalanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the qubic live service get balance params
func (o *QubicLiveServiceGetBalanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the qubic live service get balance params
func (o *QubicLiveServiceGetBalanceParams) WithID(id string) *QubicLiveServiceGetBalanceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the qubic live service get balance params
func (o *QubicLiveServiceGetBalanceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *QubicLiveServiceGetBalanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
