// Code generated by go-swagger; DO NOT EDIT.

package qubic_live_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQubicLiveServiceGetTickInfoParams creates a new QubicLiveServiceGetTickInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQubicLiveServiceGetTickInfoParams() *QubicLiveServiceGetTickInfoParams {
	return &QubicLiveServiceGetTickInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQubicLiveServiceGetTickInfoParamsWithTimeout creates a new QubicLiveServiceGetTickInfoParams object
// with the ability to set a timeout on a request.
func NewQubicLiveServiceGetTickInfoParamsWithTimeout(timeout time.Duration) *QubicLiveServiceGetTickInfoParams {
	return &QubicLiveServiceGetTickInfoParams{
		timeout: timeout,
	}
}

// NewQubicLiveServiceGetTickInfoParamsWithContext creates a new QubicLiveServiceGetTickInfoParams object
// with the ability to set a context for a request.
func NewQubicLiveServiceGetTickInfoParamsWithContext(ctx context.Context) *QubicLiveServiceGetTickInfoParams {
	return &QubicLiveServiceGetTickInfoParams{
		Context: ctx,
	}
}

// NewQubicLiveServiceGetTickInfoParamsWithHTTPClient creates a new QubicLiveServiceGetTickInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewQubicLiveServiceGetTickInfoParamsWithHTTPClient(client *http.Client) *QubicLiveServiceGetTickInfoParams {
	return &QubicLiveServiceGetTickInfoParams{
		HTTPClient: client,
	}
}

/*
QubicLiveServiceGetTickInfoParams contains all the parameters to send to the API endpoint

	for the qubic live service get tick info operation.

	Typically these are written to a http.Request.
*/
type QubicLiveServiceGetTickInfoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the qubic live service get tick info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QubicLiveServiceGetTickInfoParams) WithDefaults() *QubicLiveServiceGetTickInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the qubic live service get tick info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QubicLiveServiceGetTickInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the qubic live service get tick info params
func (o *QubicLiveServiceGetTickInfoParams) WithTimeout(timeout time.Duration) *QubicLiveServiceGetTickInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the qubic live service get tick info params
func (o *QubicLiveServiceGetTickInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the qubic live service get tick info params
func (o *QubicLiveServiceGetTickInfoParams) WithContext(ctx context.Context) *QubicLiveServiceGetTickInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the qubic live service get tick info params
func (o *QubicLiveServiceGetTickInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the qubic live service get tick info params
func (o *QubicLiveServiceGetTickInfoParams) WithHTTPClient(client *http.Client) *QubicLiveServiceGetTickInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the qubic live service get tick info params
func (o *QubicLiveServiceGetTickInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *QubicLiveServiceGetTickInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
