// Code generated by go-swagger; DO NOT EDIT.

package qubic_live_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQubicLiveServiceGetBlockHeightParams creates a new QubicLiveServiceGetBlockHeightParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQubicLiveServiceGetBlockHeightParams() *QubicLiveServiceGetBlockHeightParams {
	return &QubicLiveServiceGetBlockHeightParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQubicLiveServiceGetBlockHeightParamsWithTimeout creates a new QubicLiveServiceGetBlockHeightParams object
// with the ability to set a timeout on a request.
func NewQubicLiveServiceGetBlockHeightParamsWithTimeout(timeout time.Duration) *QubicLiveServiceGetBlockHeightParams {
	return &QubicLiveServiceGetBlockHeightParams{
		timeout: timeout,
	}
}

// NewQubicLiveServiceGetBlockHeightParamsWithContext creates a new QubicLiveServiceGetBlockHeightParams object
// with the ability to set a context for a request.
func NewQubicLiveServiceGetBlockHeightParamsWithContext(ctx context.Context) *QubicLiveServiceGetBlockHeightParams {
	return &QubicLiveServiceGetBlockHeightParams{
		Context: ctx,
	}
}

// NewQubicLiveServiceGetBlockHeightParamsWithHTTPClient creates a new QubicLiveServiceGetBlockHeightParams object
// with the ability to set a custom HTTPClient for a request.
func NewQubicLiveServiceGetBlockHeightParamsWithHTTPClient(client *http.Client) *QubicLiveServiceGetBlockHeightParams {
	return &QubicLiveServiceGetBlockHeightParams{
		HTTPClient: client,
	}
}

/*
QubicLiveServiceGetBlockHeightParams contains all the parameters to send to the API endpoint

	for the qubic live service get block height operation.

	Typically these are written to a http.Request.
*/
type QubicLiveServiceGetBlockHeightParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the qubic live service get block height params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QubicLiveServiceGetBlockHeightParams) WithDefaults() *QubicLiveServiceGetBlockHeightParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the qubic live service get block height params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QubicLiveServiceGetBlockHeightParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the qubic live service get block height params
func (o *QubicLiveServiceGetBlockHeightParams) WithTimeout(timeout time.Duration) *QubicLiveServiceGetBlockHeightParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the qubic live service get block height params
func (o *QubicLiveServiceGetBlockHeightParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the qubic live service get block height params
func (o *QubicLiveServiceGetBlockHeightParams) WithContext(ctx context.Context) *QubicLiveServiceGetBlockHeightParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the qubic live service get block height params
func (o *QubicLiveServiceGetBlockHeightParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the qubic live service get block height params
func (o *QubicLiveServiceGetBlockHeightParams) WithHTTPClient(client *http.Client) *QubicLiveServiceGetBlockHeightParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the qubic live service get block height params
func (o *QubicLiveServiceGetBlockHeightParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *QubicLiveServiceGetBlockHeightParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
