// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbBroadcastTransactionRequest pb broadcast transaction request
//
// swagger:model pbBroadcastTransactionRequest
type PbBroadcastTransactionRequest struct {

	// encoded transaction
	EncodedTransaction string `json:"encodedTransaction,omitempty"`
}

// Validate validates this pb broadcast transaction request
func (m *PbBroadcastTransactionRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb broadcast transaction request based on context it is used
func (m *PbBroadcastTransactionRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbBroadcastTransactionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbBroadcastTransactionRequest) UnmarshalBinary(b []byte) error {
	var res PbBroadcastTransactionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
