// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbBroadcastTransactionResponse pb broadcast transaction response
//
// swagger:model pbBroadcastTransactionResponse
type PbBroadcastTransactionResponse struct {

	// peers broadcasted
	PeersBroadcasted int32 `json:"peersBroadcasted,omitempty"`
}

// Validate validates this pb broadcast transaction response
func (m *PbBroadcastTransactionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb broadcast transaction response based on context it is used
func (m *PbBroadcastTransactionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbBroadcastTransactionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbBroadcastTransactionResponse) UnmarshalBinary(b []byte) error {
	var res PbBroadcastTransactionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
