// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbGetTickInfoResponse pb get tick info response
//
// swagger:model pbGetTickInfoResponse
type PbGetTickInfoResponse struct {

	// tick info
	TickInfo *PbTickInfo `json:"tickInfo,omitempty"`
}

// Validate validates this pb get tick info response
func (m *PbGetTickInfoResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTickInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PbGetTickInfoResponse) validateTickInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.TickInfo) { // not required
		return nil
	}

	if m.TickInfo != nil {
		if err := m.TickInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tickInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tickInfo")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this pb get tick info response based on the context it is used
func (m *PbGetTickInfoResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTickInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PbGetTickInfoResponse) contextValidateTickInfo(ctx context.Context, formats strfmt.Registry) error {

	if m.TickInfo != nil {

		if swag.IsZero(m.TickInfo) { // not required
			return nil
		}

		if err := m.TickInfo.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tickInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tickInfo")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PbGetTickInfoResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbGetTickInfoResponse) UnmarshalBinary(b []byte) error {
	var res PbGetTickInfoResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
