// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbTickInfo pb tick info
//
// swagger:model pbTickInfo
type PbTickInfo struct {

	// duration
	Duration int64 `json:"duration,omitempty"`

	// epoch
	Epoch int64 `json:"epoch,omitempty"`

	// initial tick
	InitialTick int64 `json:"initialTick,omitempty"`

	// tick
	Tick int64 `json:"tick,omitempty"`
}

// Validate validates this pb tick info
func (m *PbTickInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb tick info based on context it is used
func (m *PbTickInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbTickInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbTickInfo) UnmarshalBinary(b []byte) error {
	var res PbTickInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
