// Code generated by go-swagger; DO NOT EDIT.

package archive_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewArchiveServiceGetTickTransactionsParams creates a new ArchiveServiceGetTickTransactionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewArchiveServiceGetTickTransactionsParams() *ArchiveServiceGetTickTransactionsParams {
	return &ArchiveServiceGetTickTransactionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewArchiveServiceGetTickTransactionsParamsWithTimeout creates a new ArchiveServiceGetTickTransactionsParams object
// with the ability to set a timeout on a request.
func NewArchiveServiceGetTickTransactionsParamsWithTimeout(timeout time.Duration) *ArchiveServiceGetTickTransactionsParams {
	return &ArchiveServiceGetTickTransactionsParams{
		timeout: timeout,
	}
}

// NewArchiveServiceGetTickTransactionsParamsWithContext creates a new ArchiveServiceGetTickTransactionsParams object
// with the ability to set a context for a request.
func NewArchiveServiceGetTickTransactionsParamsWithContext(ctx context.Context) *ArchiveServiceGetTickTransactionsParams {
	return &ArchiveServiceGetTickTransactionsParams{
		Context: ctx,
	}
}

// NewArchiveServiceGetTickTransactionsParamsWithHTTPClient creates a new ArchiveServiceGetTickTransactionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewArchiveServiceGetTickTransactionsParamsWithHTTPClient(client *http.Client) *ArchiveServiceGetTickTransactionsParams {
	return &ArchiveServiceGetTickTransactionsParams{
		HTTPClient: client,
	}
}

/*
ArchiveServiceGetTickTransactionsParams contains all the parameters to send to the API endpoint

	for the archive service get tick transactions operation.

	Typically these are written to a http.Request.
*/
type ArchiveServiceGetTickTransactionsParams struct {

	// TickNumber.
	//
	// Format: int64
	TickNumber int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the archive service get tick transactions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArchiveServiceGetTickTransactionsParams) WithDefaults() *ArchiveServiceGetTickTransactionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the archive service get tick transactions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArchiveServiceGetTickTransactionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the archive service get tick transactions params
func (o *ArchiveServiceGetTickTransactionsParams) WithTimeout(timeout time.Duration) *ArchiveServiceGetTickTransactionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the archive service get tick transactions params
func (o *ArchiveServiceGetTickTransactionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the archive service get tick transactions params
func (o *ArchiveServiceGetTickTransactionsParams) WithContext(ctx context.Context) *ArchiveServiceGetTickTransactionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the archive service get tick transactions params
func (o *ArchiveServiceGetTickTransactionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the archive service get tick transactions params
func (o *ArchiveServiceGetTickTransactionsParams) WithHTTPClient(client *http.Client) *ArchiveServiceGetTickTransactionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the archive service get tick transactions params
func (o *ArchiveServiceGetTickTransactionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTickNumber adds the tickNumber to the archive service get tick transactions params
func (o *ArchiveServiceGetTickTransactionsParams) WithTickNumber(tickNumber int64) *ArchiveServiceGetTickTransactionsParams {
	o.SetTickNumber(tickNumber)
	return o
}

// SetTickNumber adds the tickNumber to the archive service get tick transactions params
func (o *ArchiveServiceGetTickTransactionsParams) SetTickNumber(tickNumber int64) {
	o.TickNumber = tickNumber
}

// WriteToRequest writes these params to a swagger request
func (o *ArchiveServiceGetTickTransactionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tickNumber
	if err := r.SetPathParam("tickNumber", swag.FormatInt64(o.TickNumber)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
