// Code generated by go-swagger; DO NOT EDIT.

package archive_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qubic/integration/go-clients/archive/models"
)

// ArchiveServiceGetTickTransferTransactionsReader is a Reader for the ArchiveServiceGetTickTransferTransactions structure.
type ArchiveServiceGetTickTransferTransactionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArchiveServiceGetTickTransferTransactionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArchiveServiceGetTickTransferTransactionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArchiveServiceGetTickTransferTransactionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArchiveServiceGetTickTransferTransactionsOK creates a ArchiveServiceGetTickTransferTransactionsOK with default headers values
func NewArchiveServiceGetTickTransferTransactionsOK() *ArchiveServiceGetTickTransferTransactionsOK {
	return &ArchiveServiceGetTickTransferTransactionsOK{}
}

/*
ArchiveServiceGetTickTransferTransactionsOK describes a response with status code 200, with default header values.

A successful response.
*/
type ArchiveServiceGetTickTransferTransactionsOK struct {
	Payload *models.PbGetTickTransactionsResponse
}

// IsSuccess returns true when this archive service get tick transfer transactions o k response has a 2xx status code
func (o *ArchiveServiceGetTickTransferTransactionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this archive service get tick transfer transactions o k response has a 3xx status code
func (o *ArchiveServiceGetTickTransferTransactionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this archive service get tick transfer transactions o k response has a 4xx status code
func (o *ArchiveServiceGetTickTransferTransactionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this archive service get tick transfer transactions o k response has a 5xx status code
func (o *ArchiveServiceGetTickTransferTransactionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this archive service get tick transfer transactions o k response a status code equal to that given
func (o *ArchiveServiceGetTickTransferTransactionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the archive service get tick transfer transactions o k response
func (o *ArchiveServiceGetTickTransferTransactionsOK) Code() int {
	return 200
}

func (o *ArchiveServiceGetTickTransferTransactionsOK) Error() string {
	return fmt.Sprintf("[GET /ticks/{tickNumber}/transfer-transactions][%d] archiveServiceGetTickTransferTransactionsOK  %+v", 200, o.Payload)
}

func (o *ArchiveServiceGetTickTransferTransactionsOK) String() string {
	return fmt.Sprintf("[GET /ticks/{tickNumber}/transfer-transactions][%d] archiveServiceGetTickTransferTransactionsOK  %+v", 200, o.Payload)
}

func (o *ArchiveServiceGetTickTransferTransactionsOK) GetPayload() *models.PbGetTickTransactionsResponse {
	return o.Payload
}

func (o *ArchiveServiceGetTickTransferTransactionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PbGetTickTransactionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArchiveServiceGetTickTransferTransactionsDefault creates a ArchiveServiceGetTickTransferTransactionsDefault with default headers values
func NewArchiveServiceGetTickTransferTransactionsDefault(code int) *ArchiveServiceGetTickTransferTransactionsDefault {
	return &ArchiveServiceGetTickTransferTransactionsDefault{
		_statusCode: code,
	}
}

/*
ArchiveServiceGetTickTransferTransactionsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ArchiveServiceGetTickTransferTransactionsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this archive service get tick transfer transactions default response has a 2xx status code
func (o *ArchiveServiceGetTickTransferTransactionsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this archive service get tick transfer transactions default response has a 3xx status code
func (o *ArchiveServiceGetTickTransferTransactionsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this archive service get tick transfer transactions default response has a 4xx status code
func (o *ArchiveServiceGetTickTransferTransactionsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this archive service get tick transfer transactions default response has a 5xx status code
func (o *ArchiveServiceGetTickTransferTransactionsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this archive service get tick transfer transactions default response a status code equal to that given
func (o *ArchiveServiceGetTickTransferTransactionsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the archive service get tick transfer transactions default response
func (o *ArchiveServiceGetTickTransferTransactionsDefault) Code() int {
	return o._statusCode
}

func (o *ArchiveServiceGetTickTransferTransactionsDefault) Error() string {
	return fmt.Sprintf("[GET /ticks/{tickNumber}/transfer-transactions][%d] ArchiveService_GetTickTransferTransactions default  %+v", o._statusCode, o.Payload)
}

func (o *ArchiveServiceGetTickTransferTransactionsDefault) String() string {
	return fmt.Sprintf("[GET /ticks/{tickNumber}/transfer-transactions][%d] ArchiveService_GetTickTransferTransactions default  %+v", o._statusCode, o.Payload)
}

func (o *ArchiveServiceGetTickTransferTransactionsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ArchiveServiceGetTickTransferTransactionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
