// Code generated by go-swagger; DO NOT EDIT.

package archive_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qubic/integration/go-clients/archive/models"
)

// ArchiveServiceGetStatusReader is a Reader for the ArchiveServiceGetStatus structure.
type ArchiveServiceGetStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArchiveServiceGetStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArchiveServiceGetStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArchiveServiceGetStatusDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArchiveServiceGetStatusOK creates a ArchiveServiceGetStatusOK with default headers values
func NewArchiveServiceGetStatusOK() *ArchiveServiceGetStatusOK {
	return &ArchiveServiceGetStatusOK{}
}

/*
ArchiveServiceGetStatusOK describes a response with status code 200, with default header values.

A successful response.
*/
type ArchiveServiceGetStatusOK struct {
	Payload *models.PbGetStatusResponse
}

// IsSuccess returns true when this archive service get status o k response has a 2xx status code
func (o *ArchiveServiceGetStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this archive service get status o k response has a 3xx status code
func (o *ArchiveServiceGetStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this archive service get status o k response has a 4xx status code
func (o *ArchiveServiceGetStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this archive service get status o k response has a 5xx status code
func (o *ArchiveServiceGetStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this archive service get status o k response a status code equal to that given
func (o *ArchiveServiceGetStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the archive service get status o k response
func (o *ArchiveServiceGetStatusOK) Code() int {
	return 200
}

func (o *ArchiveServiceGetStatusOK) Error() string {
	return fmt.Sprintf("[GET /status][%d] archiveServiceGetStatusOK  %+v", 200, o.Payload)
}

func (o *ArchiveServiceGetStatusOK) String() string {
	return fmt.Sprintf("[GET /status][%d] archiveServiceGetStatusOK  %+v", 200, o.Payload)
}

func (o *ArchiveServiceGetStatusOK) GetPayload() *models.PbGetStatusResponse {
	return o.Payload
}

func (o *ArchiveServiceGetStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PbGetStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArchiveServiceGetStatusDefault creates a ArchiveServiceGetStatusDefault with default headers values
func NewArchiveServiceGetStatusDefault(code int) *ArchiveServiceGetStatusDefault {
	return &ArchiveServiceGetStatusDefault{
		_statusCode: code,
	}
}

/*
ArchiveServiceGetStatusDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ArchiveServiceGetStatusDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this archive service get status default response has a 2xx status code
func (o *ArchiveServiceGetStatusDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this archive service get status default response has a 3xx status code
func (o *ArchiveServiceGetStatusDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this archive service get status default response has a 4xx status code
func (o *ArchiveServiceGetStatusDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this archive service get status default response has a 5xx status code
func (o *ArchiveServiceGetStatusDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this archive service get status default response a status code equal to that given
func (o *ArchiveServiceGetStatusDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the archive service get status default response
func (o *ArchiveServiceGetStatusDefault) Code() int {
	return o._statusCode
}

func (o *ArchiveServiceGetStatusDefault) Error() string {
	return fmt.Sprintf("[GET /status][%d] ArchiveService_GetStatus default  %+v", o._statusCode, o.Payload)
}

func (o *ArchiveServiceGetStatusDefault) String() string {
	return fmt.Sprintf("[GET /status][%d] ArchiveService_GetStatus default  %+v", o._statusCode, o.Payload)
}

func (o *ArchiveServiceGetStatusDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ArchiveServiceGetStatusDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
