// Code generated by go-swagger; DO NOT EDIT.

package archive_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewArchiveServiceGetBlockHeightParams creates a new ArchiveServiceGetBlockHeightParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewArchiveServiceGetBlockHeightParams() *ArchiveServiceGetBlockHeightParams {
	return &ArchiveServiceGetBlockHeightParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewArchiveServiceGetBlockHeightParamsWithTimeout creates a new ArchiveServiceGetBlockHeightParams object
// with the ability to set a timeout on a request.
func NewArchiveServiceGetBlockHeightParamsWithTimeout(timeout time.Duration) *ArchiveServiceGetBlockHeightParams {
	return &ArchiveServiceGetBlockHeightParams{
		timeout: timeout,
	}
}

// NewArchiveServiceGetBlockHeightParamsWithContext creates a new ArchiveServiceGetBlockHeightParams object
// with the ability to set a context for a request.
func NewArchiveServiceGetBlockHeightParamsWithContext(ctx context.Context) *ArchiveServiceGetBlockHeightParams {
	return &ArchiveServiceGetBlockHeightParams{
		Context: ctx,
	}
}

// NewArchiveServiceGetBlockHeightParamsWithHTTPClient creates a new ArchiveServiceGetBlockHeightParams object
// with the ability to set a custom HTTPClient for a request.
func NewArchiveServiceGetBlockHeightParamsWithHTTPClient(client *http.Client) *ArchiveServiceGetBlockHeightParams {
	return &ArchiveServiceGetBlockHeightParams{
		HTTPClient: client,
	}
}

/*
ArchiveServiceGetBlockHeightParams contains all the parameters to send to the API endpoint

	for the archive service get block height operation.

	Typically these are written to a http.Request.
*/
type ArchiveServiceGetBlockHeightParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the archive service get block height params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArchiveServiceGetBlockHeightParams) WithDefaults() *ArchiveServiceGetBlockHeightParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the archive service get block height params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArchiveServiceGetBlockHeightParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the archive service get block height params
func (o *ArchiveServiceGetBlockHeightParams) WithTimeout(timeout time.Duration) *ArchiveServiceGetBlockHeightParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the archive service get block height params
func (o *ArchiveServiceGetBlockHeightParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the archive service get block height params
func (o *ArchiveServiceGetBlockHeightParams) WithContext(ctx context.Context) *ArchiveServiceGetBlockHeightParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the archive service get block height params
func (o *ArchiveServiceGetBlockHeightParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the archive service get block height params
func (o *ArchiveServiceGetBlockHeightParams) WithHTTPClient(client *http.Client) *ArchiveServiceGetBlockHeightParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the archive service get block height params
func (o *ArchiveServiceGetBlockHeightParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ArchiveServiceGetBlockHeightParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
