// Code generated by go-swagger; DO NOT EDIT.

package archive_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewArchiveServiceGetComputorsParams creates a new ArchiveServiceGetComputorsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewArchiveServiceGetComputorsParams() *ArchiveServiceGetComputorsParams {
	return &ArchiveServiceGetComputorsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewArchiveServiceGetComputorsParamsWithTimeout creates a new ArchiveServiceGetComputorsParams object
// with the ability to set a timeout on a request.
func NewArchiveServiceGetComputorsParamsWithTimeout(timeout time.Duration) *ArchiveServiceGetComputorsParams {
	return &ArchiveServiceGetComputorsParams{
		timeout: timeout,
	}
}

// NewArchiveServiceGetComputorsParamsWithContext creates a new ArchiveServiceGetComputorsParams object
// with the ability to set a context for a request.
func NewArchiveServiceGetComputorsParamsWithContext(ctx context.Context) *ArchiveServiceGetComputorsParams {
	return &ArchiveServiceGetComputorsParams{
		Context: ctx,
	}
}

// NewArchiveServiceGetComputorsParamsWithHTTPClient creates a new ArchiveServiceGetComputorsParams object
// with the ability to set a custom HTTPClient for a request.
func NewArchiveServiceGetComputorsParamsWithHTTPClient(client *http.Client) *ArchiveServiceGetComputorsParams {
	return &ArchiveServiceGetComputorsParams{
		HTTPClient: client,
	}
}

/*
ArchiveServiceGetComputorsParams contains all the parameters to send to the API endpoint

	for the archive service get computors operation.

	Typically these are written to a http.Request.
*/
type ArchiveServiceGetComputorsParams struct {

	// Epoch.
	//
	// Format: int64
	Epoch int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the archive service get computors params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArchiveServiceGetComputorsParams) WithDefaults() *ArchiveServiceGetComputorsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the archive service get computors params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArchiveServiceGetComputorsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the archive service get computors params
func (o *ArchiveServiceGetComputorsParams) WithTimeout(timeout time.Duration) *ArchiveServiceGetComputorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the archive service get computors params
func (o *ArchiveServiceGetComputorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the archive service get computors params
func (o *ArchiveServiceGetComputorsParams) WithContext(ctx context.Context) *ArchiveServiceGetComputorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the archive service get computors params
func (o *ArchiveServiceGetComputorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the archive service get computors params
func (o *ArchiveServiceGetComputorsParams) WithHTTPClient(client *http.Client) *ArchiveServiceGetComputorsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the archive service get computors params
func (o *ArchiveServiceGetComputorsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEpoch adds the epoch to the archive service get computors params
func (o *ArchiveServiceGetComputorsParams) WithEpoch(epoch int64) *ArchiveServiceGetComputorsParams {
	o.SetEpoch(epoch)
	return o
}

// SetEpoch adds the epoch to the archive service get computors params
func (o *ArchiveServiceGetComputorsParams) SetEpoch(epoch int64) {
	o.Epoch = epoch
}

// WriteToRequest writes these params to a swagger request
func (o *ArchiveServiceGetComputorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param epoch
	if err := r.SetPathParam("epoch", swag.FormatInt64(o.Epoch)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
