// Code generated by go-swagger; DO NOT EDIT.

package archive_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qubic/integration/go-clients/archive/models"
)

// ArchiveServiceGetBlockHeightReader is a Reader for the ArchiveServiceGetBlockHeight structure.
type ArchiveServiceGetBlockHeightReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArchiveServiceGetBlockHeightReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArchiveServiceGetBlockHeightOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArchiveServiceGetBlockHeightDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArchiveServiceGetBlockHeightOK creates a ArchiveServiceGetBlockHeightOK with default headers values
func NewArchiveServiceGetBlockHeightOK() *ArchiveServiceGetBlockHeightOK {
	return &ArchiveServiceGetBlockHeightOK{}
}

/*
ArchiveServiceGetBlockHeightOK describes a response with status code 200, with default header values.

A successful response.
*/
type ArchiveServiceGetBlockHeightOK struct {
	Payload *models.PbGetBlockHeightResponse
}

// IsSuccess returns true when this archive service get block height o k response has a 2xx status code
func (o *ArchiveServiceGetBlockHeightOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this archive service get block height o k response has a 3xx status code
func (o *ArchiveServiceGetBlockHeightOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this archive service get block height o k response has a 4xx status code
func (o *ArchiveServiceGetBlockHeightOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this archive service get block height o k response has a 5xx status code
func (o *ArchiveServiceGetBlockHeightOK) IsServerError() bool {
	return false
}

// IsCode returns true when this archive service get block height o k response a status code equal to that given
func (o *ArchiveServiceGetBlockHeightOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the archive service get block height o k response
func (o *ArchiveServiceGetBlockHeightOK) Code() int {
	return 200
}

func (o *ArchiveServiceGetBlockHeightOK) Error() string {
	return fmt.Sprintf("[GET /block-height][%d] archiveServiceGetBlockHeightOK  %+v", 200, o.Payload)
}

func (o *ArchiveServiceGetBlockHeightOK) String() string {
	return fmt.Sprintf("[GET /block-height][%d] archiveServiceGetBlockHeightOK  %+v", 200, o.Payload)
}

func (o *ArchiveServiceGetBlockHeightOK) GetPayload() *models.PbGetBlockHeightResponse {
	return o.Payload
}

func (o *ArchiveServiceGetBlockHeightOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PbGetBlockHeightResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArchiveServiceGetBlockHeightDefault creates a ArchiveServiceGetBlockHeightDefault with default headers values
func NewArchiveServiceGetBlockHeightDefault(code int) *ArchiveServiceGetBlockHeightDefault {
	return &ArchiveServiceGetBlockHeightDefault{
		_statusCode: code,
	}
}

/*
ArchiveServiceGetBlockHeightDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ArchiveServiceGetBlockHeightDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this archive service get block height default response has a 2xx status code
func (o *ArchiveServiceGetBlockHeightDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this archive service get block height default response has a 3xx status code
func (o *ArchiveServiceGetBlockHeightDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this archive service get block height default response has a 4xx status code
func (o *ArchiveServiceGetBlockHeightDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this archive service get block height default response has a 5xx status code
func (o *ArchiveServiceGetBlockHeightDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this archive service get block height default response a status code equal to that given
func (o *ArchiveServiceGetBlockHeightDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the archive service get block height default response
func (o *ArchiveServiceGetBlockHeightDefault) Code() int {
	return o._statusCode
}

func (o *ArchiveServiceGetBlockHeightDefault) Error() string {
	return fmt.Sprintf("[GET /block-height][%d] ArchiveService_GetBlockHeight default  %+v", o._statusCode, o.Payload)
}

func (o *ArchiveServiceGetBlockHeightDefault) String() string {
	return fmt.Sprintf("[GET /block-height][%d] ArchiveService_GetBlockHeight default  %+v", o._statusCode, o.Payload)
}

func (o *ArchiveServiceGetBlockHeightDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ArchiveServiceGetBlockHeightDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
