// Code generated by go-swagger; DO NOT EDIT.

package archive_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewArchiveServiceGetChainHashParams creates a new ArchiveServiceGetChainHashParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewArchiveServiceGetChainHashParams() *ArchiveServiceGetChainHashParams {
	return &ArchiveServiceGetChainHashParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewArchiveServiceGetChainHashParamsWithTimeout creates a new ArchiveServiceGetChainHashParams object
// with the ability to set a timeout on a request.
func NewArchiveServiceGetChainHashParamsWithTimeout(timeout time.Duration) *ArchiveServiceGetChainHashParams {
	return &ArchiveServiceGetChainHashParams{
		timeout: timeout,
	}
}

// NewArchiveServiceGetChainHashParamsWithContext creates a new ArchiveServiceGetChainHashParams object
// with the ability to set a context for a request.
func NewArchiveServiceGetChainHashParamsWithContext(ctx context.Context) *ArchiveServiceGetChainHashParams {
	return &ArchiveServiceGetChainHashParams{
		Context: ctx,
	}
}

// NewArchiveServiceGetChainHashParamsWithHTTPClient creates a new ArchiveServiceGetChainHashParams object
// with the ability to set a custom HTTPClient for a request.
func NewArchiveServiceGetChainHashParamsWithHTTPClient(client *http.Client) *ArchiveServiceGetChainHashParams {
	return &ArchiveServiceGetChainHashParams{
		HTTPClient: client,
	}
}

/*
ArchiveServiceGetChainHashParams contains all the parameters to send to the API endpoint

	for the archive service get chain hash operation.

	Typically these are written to a http.Request.
*/
type ArchiveServiceGetChainHashParams struct {

	// TickNumber.
	//
	// Format: int64
	TickNumber int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the archive service get chain hash params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArchiveServiceGetChainHashParams) WithDefaults() *ArchiveServiceGetChainHashParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the archive service get chain hash params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArchiveServiceGetChainHashParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the archive service get chain hash params
func (o *ArchiveServiceGetChainHashParams) WithTimeout(timeout time.Duration) *ArchiveServiceGetChainHashParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the archive service get chain hash params
func (o *ArchiveServiceGetChainHashParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the archive service get chain hash params
func (o *ArchiveServiceGetChainHashParams) WithContext(ctx context.Context) *ArchiveServiceGetChainHashParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the archive service get chain hash params
func (o *ArchiveServiceGetChainHashParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the archive service get chain hash params
func (o *ArchiveServiceGetChainHashParams) WithHTTPClient(client *http.Client) *ArchiveServiceGetChainHashParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the archive service get chain hash params
func (o *ArchiveServiceGetChainHashParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTickNumber adds the tickNumber to the archive service get chain hash params
func (o *ArchiveServiceGetChainHashParams) WithTickNumber(tickNumber int64) *ArchiveServiceGetChainHashParams {
	o.SetTickNumber(tickNumber)
	return o
}

// SetTickNumber adds the tickNumber to the archive service get chain hash params
func (o *ArchiveServiceGetChainHashParams) SetTickNumber(tickNumber int64) {
	o.TickNumber = tickNumber
}

// WriteToRequest writes these params to a swagger request
func (o *ArchiveServiceGetChainHashParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tickNumber
	if err := r.SetPathParam("tickNumber", swag.FormatInt64(o.TickNumber)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
