// Code generated by go-swagger; DO NOT EDIT.

package archive_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qubic/integration/go-clients/archive/models"
)

// ArchiveServiceGetQuorumTickDataReader is a Reader for the ArchiveServiceGetQuorumTickData structure.
type ArchiveServiceGetQuorumTickDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArchiveServiceGetQuorumTickDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArchiveServiceGetQuorumTickDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArchiveServiceGetQuorumTickDataDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArchiveServiceGetQuorumTickDataOK creates a ArchiveServiceGetQuorumTickDataOK with default headers values
func NewArchiveServiceGetQuorumTickDataOK() *ArchiveServiceGetQuorumTickDataOK {
	return &ArchiveServiceGetQuorumTickDataOK{}
}

/*
ArchiveServiceGetQuorumTickDataOK describes a response with status code 200, with default header values.

A successful response.
*/
type ArchiveServiceGetQuorumTickDataOK struct {
	Payload *models.PbGetQuorumTickDataResponse
}

// IsSuccess returns true when this archive service get quorum tick data o k response has a 2xx status code
func (o *ArchiveServiceGetQuorumTickDataOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this archive service get quorum tick data o k response has a 3xx status code
func (o *ArchiveServiceGetQuorumTickDataOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this archive service get quorum tick data o k response has a 4xx status code
func (o *ArchiveServiceGetQuorumTickDataOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this archive service get quorum tick data o k response has a 5xx status code
func (o *ArchiveServiceGetQuorumTickDataOK) IsServerError() bool {
	return false
}

// IsCode returns true when this archive service get quorum tick data o k response a status code equal to that given
func (o *ArchiveServiceGetQuorumTickDataOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the archive service get quorum tick data o k response
func (o *ArchiveServiceGetQuorumTickDataOK) Code() int {
	return 200
}

func (o *ArchiveServiceGetQuorumTickDataOK) Error() string {
	return fmt.Sprintf("[GET /ticks/{tickNumber}/quorum-tick-data][%d] archiveServiceGetQuorumTickDataOK  %+v", 200, o.Payload)
}

func (o *ArchiveServiceGetQuorumTickDataOK) String() string {
	return fmt.Sprintf("[GET /ticks/{tickNumber}/quorum-tick-data][%d] archiveServiceGetQuorumTickDataOK  %+v", 200, o.Payload)
}

func (o *ArchiveServiceGetQuorumTickDataOK) GetPayload() *models.PbGetQuorumTickDataResponse {
	return o.Payload
}

func (o *ArchiveServiceGetQuorumTickDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PbGetQuorumTickDataResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArchiveServiceGetQuorumTickDataDefault creates a ArchiveServiceGetQuorumTickDataDefault with default headers values
func NewArchiveServiceGetQuorumTickDataDefault(code int) *ArchiveServiceGetQuorumTickDataDefault {
	return &ArchiveServiceGetQuorumTickDataDefault{
		_statusCode: code,
	}
}

/*
ArchiveServiceGetQuorumTickDataDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ArchiveServiceGetQuorumTickDataDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this archive service get quorum tick data default response has a 2xx status code
func (o *ArchiveServiceGetQuorumTickDataDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this archive service get quorum tick data default response has a 3xx status code
func (o *ArchiveServiceGetQuorumTickDataDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this archive service get quorum tick data default response has a 4xx status code
func (o *ArchiveServiceGetQuorumTickDataDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this archive service get quorum tick data default response has a 5xx status code
func (o *ArchiveServiceGetQuorumTickDataDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this archive service get quorum tick data default response a status code equal to that given
func (o *ArchiveServiceGetQuorumTickDataDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the archive service get quorum tick data default response
func (o *ArchiveServiceGetQuorumTickDataDefault) Code() int {
	return o._statusCode
}

func (o *ArchiveServiceGetQuorumTickDataDefault) Error() string {
	return fmt.Sprintf("[GET /ticks/{tickNumber}/quorum-tick-data][%d] ArchiveService_GetQuorumTickData default  %+v", o._statusCode, o.Payload)
}

func (o *ArchiveServiceGetQuorumTickDataDefault) String() string {
	return fmt.Sprintf("[GET /ticks/{tickNumber}/quorum-tick-data][%d] ArchiveService_GetQuorumTickData default  %+v", o._statusCode, o.Payload)
}

func (o *ArchiveServiceGetQuorumTickDataDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ArchiveServiceGetQuorumTickDataDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
