// Code generated by go-swagger; DO NOT EDIT.

package archive_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qubic/integration/UseCases/go-clients/archive/models"
)

// ArchiveServiceGetTickTransactionsReader is a Reader for the ArchiveServiceGetTickTransactions structure.
type ArchiveServiceGetTickTransactionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArchiveServiceGetTickTransactionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArchiveServiceGetTickTransactionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArchiveServiceGetTickTransactionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArchiveServiceGetTickTransactionsOK creates a ArchiveServiceGetTickTransactionsOK with default headers values
func NewArchiveServiceGetTickTransactionsOK() *ArchiveServiceGetTickTransactionsOK {
	return &ArchiveServiceGetTickTransactionsOK{}
}

/*
ArchiveServiceGetTickTransactionsOK describes a response with status code 200, with default header values.

A successful response.
*/
type ArchiveServiceGetTickTransactionsOK struct {
	Payload *models.PbGetTickTransactionsResponse
}

// IsSuccess returns true when this archive service get tick transactions o k response has a 2xx status code
func (o *ArchiveServiceGetTickTransactionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this archive service get tick transactions o k response has a 3xx status code
func (o *ArchiveServiceGetTickTransactionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this archive service get tick transactions o k response has a 4xx status code
func (o *ArchiveServiceGetTickTransactionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this archive service get tick transactions o k response has a 5xx status code
func (o *ArchiveServiceGetTickTransactionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this archive service get tick transactions o k response a status code equal to that given
func (o *ArchiveServiceGetTickTransactionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the archive service get tick transactions o k response
func (o *ArchiveServiceGetTickTransactionsOK) Code() int {
	return 200
}

func (o *ArchiveServiceGetTickTransactionsOK) Error() string {
	return fmt.Sprintf("[GET /ticks/{tickNumber}/transactions][%d] archiveServiceGetTickTransactionsOK  %+v", 200, o.Payload)
}

func (o *ArchiveServiceGetTickTransactionsOK) String() string {
	return fmt.Sprintf("[GET /ticks/{tickNumber}/transactions][%d] archiveServiceGetTickTransactionsOK  %+v", 200, o.Payload)
}

func (o *ArchiveServiceGetTickTransactionsOK) GetPayload() *models.PbGetTickTransactionsResponse {
	return o.Payload
}

func (o *ArchiveServiceGetTickTransactionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PbGetTickTransactionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArchiveServiceGetTickTransactionsDefault creates a ArchiveServiceGetTickTransactionsDefault with default headers values
func NewArchiveServiceGetTickTransactionsDefault(code int) *ArchiveServiceGetTickTransactionsDefault {
	return &ArchiveServiceGetTickTransactionsDefault{
		_statusCode: code,
	}
}

/*
ArchiveServiceGetTickTransactionsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ArchiveServiceGetTickTransactionsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this archive service get tick transactions default response has a 2xx status code
func (o *ArchiveServiceGetTickTransactionsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this archive service get tick transactions default response has a 3xx status code
func (o *ArchiveServiceGetTickTransactionsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this archive service get tick transactions default response has a 4xx status code
func (o *ArchiveServiceGetTickTransactionsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this archive service get tick transactions default response has a 5xx status code
func (o *ArchiveServiceGetTickTransactionsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this archive service get tick transactions default response a status code equal to that given
func (o *ArchiveServiceGetTickTransactionsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the archive service get tick transactions default response
func (o *ArchiveServiceGetTickTransactionsDefault) Code() int {
	return o._statusCode
}

func (o *ArchiveServiceGetTickTransactionsDefault) Error() string {
	return fmt.Sprintf("[GET /ticks/{tickNumber}/transactions][%d] ArchiveService_GetTickTransactions default  %+v", o._statusCode, o.Payload)
}

func (o *ArchiveServiceGetTickTransactionsDefault) String() string {
	return fmt.Sprintf("[GET /ticks/{tickNumber}/transactions][%d] ArchiveService_GetTickTransactions default  %+v", o._statusCode, o.Payload)
}

func (o *ArchiveServiceGetTickTransactionsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ArchiveServiceGetTickTransactionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
