// Code generated by go-swagger; DO NOT EDIT.

package archive_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewArchiveServiceGetTickDataParams creates a new ArchiveServiceGetTickDataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewArchiveServiceGetTickDataParams() *ArchiveServiceGetTickDataParams {
	return &ArchiveServiceGetTickDataParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewArchiveServiceGetTickDataParamsWithTimeout creates a new ArchiveServiceGetTickDataParams object
// with the ability to set a timeout on a request.
func NewArchiveServiceGetTickDataParamsWithTimeout(timeout time.Duration) *ArchiveServiceGetTickDataParams {
	return &ArchiveServiceGetTickDataParams{
		timeout: timeout,
	}
}

// NewArchiveServiceGetTickDataParamsWithContext creates a new ArchiveServiceGetTickDataParams object
// with the ability to set a context for a request.
func NewArchiveServiceGetTickDataParamsWithContext(ctx context.Context) *ArchiveServiceGetTickDataParams {
	return &ArchiveServiceGetTickDataParams{
		Context: ctx,
	}
}

// NewArchiveServiceGetTickDataParamsWithHTTPClient creates a new ArchiveServiceGetTickDataParams object
// with the ability to set a custom HTTPClient for a request.
func NewArchiveServiceGetTickDataParamsWithHTTPClient(client *http.Client) *ArchiveServiceGetTickDataParams {
	return &ArchiveServiceGetTickDataParams{
		HTTPClient: client,
	}
}

/*
ArchiveServiceGetTickDataParams contains all the parameters to send to the API endpoint

	for the archive service get tick data operation.

	Typically these are written to a http.Request.
*/
type ArchiveServiceGetTickDataParams struct {

	// TickNumber.
	//
	// Format: int64
	TickNumber int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the archive service get tick data params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArchiveServiceGetTickDataParams) WithDefaults() *ArchiveServiceGetTickDataParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the archive service get tick data params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArchiveServiceGetTickDataParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the archive service get tick data params
func (o *ArchiveServiceGetTickDataParams) WithTimeout(timeout time.Duration) *ArchiveServiceGetTickDataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the archive service get tick data params
func (o *ArchiveServiceGetTickDataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the archive service get tick data params
func (o *ArchiveServiceGetTickDataParams) WithContext(ctx context.Context) *ArchiveServiceGetTickDataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the archive service get tick data params
func (o *ArchiveServiceGetTickDataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the archive service get tick data params
func (o *ArchiveServiceGetTickDataParams) WithHTTPClient(client *http.Client) *ArchiveServiceGetTickDataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the archive service get tick data params
func (o *ArchiveServiceGetTickDataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTickNumber adds the tickNumber to the archive service get tick data params
func (o *ArchiveServiceGetTickDataParams) WithTickNumber(tickNumber int64) *ArchiveServiceGetTickDataParams {
	o.SetTickNumber(tickNumber)
	return o
}

// SetTickNumber adds the tickNumber to the archive service get tick data params
func (o *ArchiveServiceGetTickDataParams) SetTickNumber(tickNumber int64) {
	o.TickNumber = tickNumber
}

// WriteToRequest writes these params to a swagger request
func (o *ArchiveServiceGetTickDataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tickNumber
	if err := r.SetPathParam("tickNumber", swag.FormatInt64(o.TickNumber)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
