// Code generated by go-swagger; DO NOT EDIT.

package archive_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qubic/integration/go-clients/archive/models"
)

// ArchiveServiceGetComputorsReader is a Reader for the ArchiveServiceGetComputors structure.
type ArchiveServiceGetComputorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArchiveServiceGetComputorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArchiveServiceGetComputorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArchiveServiceGetComputorsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArchiveServiceGetComputorsOK creates a ArchiveServiceGetComputorsOK with default headers values
func NewArchiveServiceGetComputorsOK() *ArchiveServiceGetComputorsOK {
	return &ArchiveServiceGetComputorsOK{}
}

/*
ArchiveServiceGetComputorsOK describes a response with status code 200, with default header values.

A successful response.
*/
type ArchiveServiceGetComputorsOK struct {
	Payload *models.PbGetComputorsResponse
}

// IsSuccess returns true when this archive service get computors o k response has a 2xx status code
func (o *ArchiveServiceGetComputorsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this archive service get computors o k response has a 3xx status code
func (o *ArchiveServiceGetComputorsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this archive service get computors o k response has a 4xx status code
func (o *ArchiveServiceGetComputorsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this archive service get computors o k response has a 5xx status code
func (o *ArchiveServiceGetComputorsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this archive service get computors o k response a status code equal to that given
func (o *ArchiveServiceGetComputorsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the archive service get computors o k response
func (o *ArchiveServiceGetComputorsOK) Code() int {
	return 200
}

func (o *ArchiveServiceGetComputorsOK) Error() string {
	return fmt.Sprintf("[GET /epochs/{epoch}/computors][%d] archiveServiceGetComputorsOK  %+v", 200, o.Payload)
}

func (o *ArchiveServiceGetComputorsOK) String() string {
	return fmt.Sprintf("[GET /epochs/{epoch}/computors][%d] archiveServiceGetComputorsOK  %+v", 200, o.Payload)
}

func (o *ArchiveServiceGetComputorsOK) GetPayload() *models.PbGetComputorsResponse {
	return o.Payload
}

func (o *ArchiveServiceGetComputorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PbGetComputorsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArchiveServiceGetComputorsDefault creates a ArchiveServiceGetComputorsDefault with default headers values
func NewArchiveServiceGetComputorsDefault(code int) *ArchiveServiceGetComputorsDefault {
	return &ArchiveServiceGetComputorsDefault{
		_statusCode: code,
	}
}

/*
ArchiveServiceGetComputorsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ArchiveServiceGetComputorsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this archive service get computors default response has a 2xx status code
func (o *ArchiveServiceGetComputorsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this archive service get computors default response has a 3xx status code
func (o *ArchiveServiceGetComputorsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this archive service get computors default response has a 4xx status code
func (o *ArchiveServiceGetComputorsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this archive service get computors default response has a 5xx status code
func (o *ArchiveServiceGetComputorsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this archive service get computors default response a status code equal to that given
func (o *ArchiveServiceGetComputorsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the archive service get computors default response
func (o *ArchiveServiceGetComputorsDefault) Code() int {
	return o._statusCode
}

func (o *ArchiveServiceGetComputorsDefault) Error() string {
	return fmt.Sprintf("[GET /epochs/{epoch}/computors][%d] ArchiveService_GetComputors default  %+v", o._statusCode, o.Payload)
}

func (o *ArchiveServiceGetComputorsDefault) String() string {
	return fmt.Sprintf("[GET /epochs/{epoch}/computors][%d] ArchiveService_GetComputors default  %+v", o._statusCode, o.Payload)
}

func (o *ArchiveServiceGetComputorsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ArchiveServiceGetComputorsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
