// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbComputors pb computors
//
// swagger:model pbComputors
type PbComputors struct {

	// epoch
	Epoch int64 `json:"epoch,omitempty"`

	// identities
	Identities []string `json:"identities"`

	// signature hex
	SignatureHex string `json:"signatureHex,omitempty"`
}

// Validate validates this pb computors
func (m *PbComputors) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb computors based on context it is used
func (m *PbComputors) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbComputors) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbComputors) UnmarshalBinary(b []byte) error {
	var res PbComputors
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
