// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbGetTickDataResponse pb get tick data response
//
// swagger:model pbGetTickDataResponse
type PbGetTickDataResponse struct {

	// tick data
	TickData *PbTickData `json:"tickData,omitempty"`
}

// Validate validates this pb get tick data response
func (m *PbGetTickDataResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTickData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PbGetTickDataResponse) validateTickData(formats strfmt.Registry) error {
	if swag.IsZero(m.TickData) { // not required
		return nil
	}

	if m.TickData != nil {
		if err := m.TickData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tickData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tickData")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this pb get tick data response based on the context it is used
func (m *PbGetTickDataResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTickData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PbGetTickDataResponse) contextValidateTickData(ctx context.Context, formats strfmt.Registry) error {

	if m.TickData != nil {

		if swag.IsZero(m.TickData) { // not required
			return nil
		}

		if err := m.TickData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tickData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tickData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PbGetTickDataResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbGetTickDataResponse) UnmarshalBinary(b []byte) error {
	var res PbGetTickDataResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
