// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbGetChainHashResponse pb get chain hash response
//
// swagger:model pbGetChainHashResponse
type PbGetChainHashResponse struct {

	// hex digest
	HexDigest string `json:"hexDigest,omitempty"`
}

// Validate validates this pb get chain hash response
func (m *PbGetChainHashResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb get chain hash response based on context it is used
func (m *PbGetChainHashResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbGetChainHashResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbGetChainHashResponse) UnmarshalBinary(b []byte) error {
	var res PbGetChainHashResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
