// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbGetComputorsResponse pb get computors response
//
// swagger:model pbGetComputorsResponse
type PbGetComputorsResponse struct {

	// computors
	Computors *PbComputors `json:"computors,omitempty"`
}

// Validate validates this pb get computors response
func (m *PbGetComputorsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateComputors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PbGetComputorsResponse) validateComputors(formats strfmt.Registry) error {
	if swag.IsZero(m.Computors) { // not required
		return nil
	}

	if m.Computors != nil {
		if err := m.Computors.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("computors")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("computors")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this pb get computors response based on the context it is used
func (m *PbGetComputorsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateComputors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PbGetComputorsResponse) contextValidateComputors(ctx context.Context, formats strfmt.Registry) error {

	if m.Computors != nil {

		if swag.IsZero(m.Computors) { // not required
			return nil
		}

		if err := m.Computors.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("computors")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("computors")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PbGetComputorsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbGetComputorsResponse) UnmarshalBinary(b []byte) error {
	var res PbGetComputorsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
