// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbProcessedTick pb processed tick
//
// swagger:model pbProcessedTick
type PbProcessedTick struct {

	// epoch
	Epoch int64 `json:"epoch,omitempty"`

	// tick number
	TickNumber int64 `json:"tickNumber,omitempty"`
}

// Validate validates this pb processed tick
func (m *PbProcessedTick) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb processed tick based on context it is used
func (m *PbProcessedTick) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbProcessedTick) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbProcessedTick) UnmarshalBinary(b []byte) error {
	var res PbProcessedTick
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
