// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbQuorumTickStructure pb quorum tick structure
//
// swagger:model pbQuorumTickStructure
type PbQuorumTickStructure struct {

	// epoch
	Epoch int64 `json:"epoch,omitempty"`

	// prev computer digest hex
	PrevComputerDigestHex string `json:"prevComputerDigestHex,omitempty"`

	// prev resource testing digest hex
	PrevResourceTestingDigestHex string `json:"prevResourceTestingDigestHex,omitempty"`

	// prev spectrum digest hex
	PrevSpectrumDigestHex string `json:"prevSpectrumDigestHex,omitempty"`

	// prev universe digest hex
	PrevUniverseDigestHex string `json:"prevUniverseDigestHex,omitempty"`

	// tick number
	TickNumber int64 `json:"tickNumber,omitempty"`

	// timestamp
	Timestamp string `json:"timestamp,omitempty"`

	// tx digest hex
	TxDigestHex string `json:"txDigestHex,omitempty"`
}

// Validate validates this pb quorum tick structure
func (m *PbQuorumTickStructure) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb quorum tick structure based on context it is used
func (m *PbQuorumTickStructure) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbQuorumTickStructure) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbQuorumTickStructure) UnmarshalBinary(b []byte) error {
	var res PbQuorumTickStructure
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
