// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbQuorumDiff pb quorum diff
//
// swagger:model pbQuorumDiff
type PbQuorumDiff struct {

	// expected next tick tx digest hex
	ExpectedNextTickTxDigestHex string `json:"expectedNextTickTxDigestHex,omitempty"`

	// salted computer digest hex
	SaltedComputerDigestHex string `json:"saltedComputerDigestHex,omitempty"`

	// salted resource testing digest hex
	SaltedResourceTestingDigestHex string `json:"saltedResourceTestingDigestHex,omitempty"`

	// salted spectrum digest hex
	SaltedSpectrumDigestHex string `json:"saltedSpectrumDigestHex,omitempty"`

	// salted universe digest hex
	SaltedUniverseDigestHex string `json:"saltedUniverseDigestHex,omitempty"`

	// signature hex
	SignatureHex string `json:"signatureHex,omitempty"`
}

// Validate validates this pb quorum diff
func (m *PbQuorumDiff) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb quorum diff based on context it is used
func (m *PbQuorumDiff) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbQuorumDiff) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbQuorumDiff) UnmarshalBinary(b []byte) error {
	var res PbQuorumDiff
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
