name: Update API Docs

on:
  workflow_dispatch: # Manual trigger
  repository_dispatch: # Trigger from other repos
    types: [live-api-update, query-api-update]

jobs:
  live-api-update:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'live-api-update'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v6

      - name: Decode Live API OpenAPI spec from payload
        run: |
          echo "${{ github.event.client_payload.openapi_spec_base64 }}" | base64 -d > Partners/swagger/qubic-http.openapi.yaml

      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Partners/swagger/qubic-http.openapi.yaml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Live API Docs" && git push)

  query-api-update:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'query-api-update'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v6

      - name: Decode Query API OpenAPI spec from payload
        run: |
          echo "${{ github.event.client_payload.openapi_spec_base64 }}" | base64 -d > Partners/swagger/query_services.openapi.yaml

      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Partners/swagger/query_services.openapi.yaml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Query API Docs" && git push)
